-- "AULA 15 - "ADICIONANDO LINHA "
-- Começando a aula já deixando selecionadO o banco de dados que vou usar para fazer o uso dos operadores
-- ADICIONANDO LINHA A TABELA

-- MODELO INSERT INTO
USE sakila;

SELECT * FROM actor; -- COMANDO QUE FAZ RETORNAR A TABELA DEPOIS DA INSERÇÃO
INSERT INTO actor
	VALUE (DEFAULT, 'RAUL', 'OLIVEIRA', '2006-02-15 04:34:33') -- LEMBRANDO QUE É OBRIGATÓRIO SEGUIR O MESMO PADRÃO DA TABELA QUE VOCE 
															   -- ESTÁ INSERINDO DADOS, MESMA ORDEM, OBEDECENDO OS DADOS OBRIGATÓRIOS